import {anagramTest} from './anagram.test';
import { binarySearchTest } from './binarySearch.test';
import { bubbleSortTest } from './bubbleSort.test';
import { deepCloneTest } from './deepClone.test';
import { deepEqualsTest } from './deepEquals.test';
import { deepMergeTest } from './deepMerge.test';
import { fizzbuzzTest } from './fizzbuzz.test';
import { heapTest } from './heap.test';
import { heapSortTest } from './heapSort.test';
import { insertionSortTest } from './insertionSort.test';
import { isEmptyTest } from './isEmpty.test';
import { linkedListTest } from './linkedList.test';
import { mergeArraysTest } from './mergeArrays.test';
import { mergeSortTest } from './mergeSort.test';
import { palindromeTest } from './palindrome.test';
import { queueTest } from './queue.test';
import { quickSortTest } from './quickSort.test';
import { repeatedItemTest } from './repeatedItem.test';
import { romanTest } from './roman.test';
import { stackTest } from './stack.test';


anagramTest();
binarySearchTest();
deepMergeTest();
bubbleSortTest();
deepCloneTest();
deepEqualsTest();
fizzbuzzTest();
heapTest();
heapSortTest();
insertionSortTest();
isEmptyTest();
linkedListTest();
mergeArraysTest();
mergeSortTest();
palindromeTest();
queueTest();
quickSortTest();
repeatedItemTest();
romanTest();
stackTest();
